SELECT P.IDPRODUTO AS PIDPRODUTO,
  P.NOME AS NOMEPRODUTO,
  PI.SITUACAO,
  PED.DATAPEDIDO,
  MONTHS_BETWEEN((SELECT CURRENT_TIMESTAMP FROM DUAL), PED.DATAPEDIDO)
  FROM PRODUTO P
  INNER JOIN PEDIDOITEM PI ON P.IDPRODUTO = PI.IDPRODUTO
  INNER JOIN PEDIDO PED ON PED.IDPEDIDO = PI.IDPEDIDO
  WHERE MONTHS_BETWEEN((SELECT CURRENT_TIMESTAMP FROM DUAL), PED.DATAPEDIDO) < 4;
  
SELECT PI.IDPRODUTO AS IDPEDIDO,
  PED.DATAPEDIDO,
  MONTHS_BETWEEN((SELECT CURRENT_TIMESTAMP FROM DUAL), DATAPEDIDO)
  FROM PEDIDO PED
  INNER JOIN PEDIDOITEM PI ON PED.IDPEDIDO = PI.IDPEDIDO
  WHERE MONTHS_BETWEEN((SELECT CURRENT_TIMESTAMP FROM DUAL), DATAPEDIDO) < 4 AND MONTHS_BETWEEN((SELECT CURRENT_TIMESTAMP FROM DUAL), DATAPEDIDO) > 0;
